package DataTransferLayer;
// default package
// Generated 2017-02-28 18:17:33 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.sql.Clob;

/**
 * BiographyId generated by hbm2java
 */
public class BiographyId implements java.io.Serializable {

	private BigDecimal crewmemberid;
	private Clob description;

	public BiographyId() {
	}

	public BiographyId(BigDecimal crewmemberid, Clob description) {
		this.crewmemberid = crewmemberid;
		this.description = description;
	}

	public BigDecimal getCrewmemberid() {
		return this.crewmemberid;
	}

	public void setCrewmemberid(BigDecimal crewmemberid) {
		this.crewmemberid = crewmemberid;
	}

	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BiographyId))
			return false;
		BiographyId castOther = (BiographyId) other;

		return ((this.getCrewmemberid() == castOther.getCrewmemberid()) || (this.getCrewmemberid() != null
				&& castOther.getCrewmemberid() != null && this.getCrewmemberid().equals(castOther.getCrewmemberid())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCrewmemberid() == null ? 0 : this.getCrewmemberid().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		return result;
	}

}
