package DataTransferLayer;
// default package
// Generated 2017-02-28 18:17:33 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private BigDecimal systemuserid;
	private Systemuser systemuser;
	private String matricule;

	public Employee() {
	}

	public Employee(Systemuser systemuser, String matricule) {
		this.systemuser = systemuser;
		this.matricule = matricule;
	}

	public BigDecimal getSystemuserid() {
		return this.systemuserid;
	}

	public void setSystemuserid(BigDecimal systemuserid) {
		this.systemuserid = systemuserid;
	}

	public Systemuser getSystemuser() {
		return this.systemuser;
	}

	public void setSystemuser(Systemuser systemuser) {
		this.systemuser = systemuser;
	}

	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

}
