package DataTransferLayer;
// default package
// Generated 2017-02-28 18:17:33 by Hibernate Tools 4.3.1.Final

/**
 * Movieactor generated by hbm2java
 */
public class Movieactor implements java.io.Serializable {

	private MovieactorId id;
	private Movie movie;
	private Crewmember crewmember;

	public Movieactor() {
	}

	public Movieactor(MovieactorId id, Movie movie, Crewmember crewmember) {
		this.id = id;
		this.movie = movie;
		this.crewmember = crewmember;
	}

	public MovieactorId getId() {
		return this.id;
	}

	public void setId(MovieactorId id) {
		this.id = id;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public Crewmember getCrewmember() {
		return this.crewmember;
	}

	public void setCrewmember(Crewmember crewmember) {
		this.crewmember = crewmember;
	}

}
