package DataTransferLayer;
// default package
// Generated 2017-02-28 18:17:33 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private String provincecode;
	private String name;
	private Set systemusers = new HashSet(0);

	public Province() {
	}

	public Province(String provincecode, String name) {
		this.provincecode = provincecode;
		this.name = name;
	}

	public Province(String provincecode, String name, Set systemusers) {
		this.provincecode = provincecode;
		this.name = name;
		this.systemusers = systemusers;
	}

	public String getProvincecode() {
		return this.provincecode;
	}

	public void setProvincecode(String provincecode) {
		this.provincecode = provincecode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getSystemusers() {
		return this.systemusers;
	}

	public void setSystemusers(Set systemusers) {
		this.systemusers = systemusers;
	}

}
