package DataTransferLayer;
// default package
// Generated 2017-02-28 18:17:33 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Synopsis generated by hbm2java
 */
public class Synopsis implements java.io.Serializable {

	private BigDecimal synopsisid;
	private String description;
	private Set movies = new HashSet(0);

	public Synopsis() {
	}

	public Synopsis(BigDecimal synopsisid, String description) {
		this.synopsisid = synopsisid;
		this.description = description;
	}

	public Synopsis(BigDecimal synopsisid, String description, Set movies) {
		this.synopsisid = synopsisid;
		this.description = description;
		this.movies = movies;
	}

	public BigDecimal getSynopsisid() {
		return this.synopsisid;
	}

	public void setSynopsisid(BigDecimal synopsisid) {
		this.synopsisid = synopsisid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getMovies() {
		return this.movies;
	}

	public void setMovies(Set movies) {
		this.movies = movies;
	}

}
