// default package
// Generated Mar 1, 2017 4:12:55 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;

/**
 * Biography generated by hbm2java
 */
public class Biography implements java.io.Serializable {

	private BigDecimal biographyid;
	private Crewmember crewmember;
	private Clob description;

	public Biography() {
	}

	public Biography(BigDecimal biographyid, Crewmember crewmember, Clob description) {
		this.biographyid = biographyid;
		this.crewmember = crewmember;
		this.description = description;
	}

	public BigDecimal getBiographyid() {
		return this.biographyid;
	}

	public void setBiographyid(BigDecimal biographyid) {
		this.biographyid = biographyid;
	}

	public Crewmember getCrewmember() {
		return this.crewmember;
	}

	public void setCrewmember(Crewmember crewmember) {
		this.crewmember = crewmember;
	}

	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

}
