// default package
// Generated 2017-02-28 18:17:33 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Crewmember generated by hbm2java
 */
public class Crewmember implements java.io.Serializable {

	private BigDecimal crewmemberid;
	private String lastname;
	private String firstname;
	private Date birthdate;
	private String photo;
	private String type;
	private String birthplace;
	private Set movieactors = new HashSet(0);
	private Set movies = new HashSet(0);
	private Set biographies = new HashSet(0);

	public Crewmember() {
	}

	public Crewmember(BigDecimal crewmemberid) {
		this.crewmemberid = crewmemberid;
	}

	public Crewmember(BigDecimal crewmemberid, String lastname, String firstname, Date birthdate, String photo,
			String type, String birthplace, Set movieactors, Set movies, Set biographies) {
		this.crewmemberid = crewmemberid;
		this.lastname = lastname;
		this.firstname = firstname;
		this.birthdate = birthdate;
		this.photo = photo;
		this.type = type;
		this.birthplace = birthplace;
		this.movieactors = movieactors;
		this.movies = movies;
		this.biographies = biographies;
	}

	public BigDecimal getCrewmemberid() {
		return this.crewmemberid;
	}

	public void setCrewmemberid(BigDecimal crewmemberid) {
		this.crewmemberid = crewmemberid;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getBirthplace() {
		return this.birthplace;
	}

	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	public Set getMovieactors() {
		return this.movieactors;
	}

	public void setMovieactors(Set movieactors) {
		this.movieactors = movieactors;
	}

	public Set getMovies() {
		return this.movies;
	}

	public void setMovies(Set movies) {
		this.movies = movies;
	}

	public Set getBiographies() {
		return this.biographies;
	}

	public void setBiographies(Set biographies) {
		this.biographies = biographies;
	}

}
