// default package
// Generated 2017-02-28 18:17:33 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre implements java.io.Serializable {

	private BigDecimal genreid;
	private String name;
	private String description;
	private Set movies = new HashSet(0);

	public Genre() {
	}

	public Genre(BigDecimal genreid) {
		this.genreid = genreid;
	}

	public Genre(BigDecimal genreid, String name, String description, Set movies) {
		this.genreid = genreid;
		this.name = name;
		this.description = description;
		this.movies = movies;
	}

	public BigDecimal getGenreid() {
		return this.genreid;
	}

	public void setGenreid(BigDecimal genreid) {
		this.genreid = genreid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getMovies() {
		return this.movies;
	}

	public void setMovies(Set movies) {
		this.movies = movies;
	}

}
