// default package
// Generated Mar 1, 2017 4:12:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * Movieactor generated by hbm2java
 */
public class Movieactor implements java.io.Serializable {

	private MovieactorId id;
	private Crewmember crewmember;
	private Movie movie;

	public Movieactor() {
	}

	public Movieactor(MovieactorId id, Crewmember crewmember, Movie movie) {
		this.id = id;
		this.crewmember = crewmember;
		this.movie = movie;
	}

	public MovieactorId getId() {
		return this.id;
	}

	public void setId(MovieactorId id) {
		this.id = id;
	}

	public Crewmember getCrewmember() {
		return this.crewmember;
	}

	public void setCrewmember(Crewmember crewmember) {
		this.crewmember = crewmember;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

}
