// default package
// Generated 2017-02-28 18:17:33 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * MoviecopyId generated by hbm2java
 */
public class MoviecopyId implements java.io.Serializable {

	private BigDecimal movieid;
	private BigDecimal systemuserid;
	private String moviecode;
	private BigDecimal availableamount;
	private Date rentaldate;

	public MoviecopyId() {
	}

	public MoviecopyId(BigDecimal movieid, BigDecimal availableamount) {
		this.movieid = movieid;
		this.availableamount = availableamount;
	}

	public MoviecopyId(BigDecimal movieid, BigDecimal systemuserid, String moviecode, BigDecimal availableamount,
			Date rentaldate) {
		this.movieid = movieid;
		this.systemuserid = systemuserid;
		this.moviecode = moviecode;
		this.availableamount = availableamount;
		this.rentaldate = rentaldate;
	}

	public BigDecimal getMovieid() {
		return this.movieid;
	}

	public void setMovieid(BigDecimal movieid) {
		this.movieid = movieid;
	}

	public BigDecimal getSystemuserid() {
		return this.systemuserid;
	}

	public void setSystemuserid(BigDecimal systemuserid) {
		this.systemuserid = systemuserid;
	}

	public String getMoviecode() {
		return this.moviecode;
	}

	public void setMoviecode(String moviecode) {
		this.moviecode = moviecode;
	}

	public BigDecimal getAvailableamount() {
		return this.availableamount;
	}

	public void setAvailableamount(BigDecimal availableamount) {
		this.availableamount = availableamount;
	}

	public Date getRentaldate() {
		return this.rentaldate;
	}

	public void setRentaldate(Date rentaldate) {
		this.rentaldate = rentaldate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MoviecopyId))
			return false;
		MoviecopyId castOther = (MoviecopyId) other;

		return ((this.getMovieid() == castOther.getMovieid()) || (this.getMovieid() != null
				&& castOther.getMovieid() != null && this.getMovieid().equals(castOther.getMovieid())))
				&& ((this.getSystemuserid() == castOther.getSystemuserid())
						|| (this.getSystemuserid() != null && castOther.getSystemuserid() != null
								&& this.getSystemuserid().equals(castOther.getSystemuserid())))
				&& ((this.getMoviecode() == castOther.getMoviecode()) || (this.getMoviecode() != null
						&& castOther.getMoviecode() != null && this.getMoviecode().equals(castOther.getMoviecode())))
				&& ((this.getAvailableamount() == castOther.getAvailableamount())
						|| (this.getAvailableamount() != null && castOther.getAvailableamount() != null
								&& this.getAvailableamount().equals(castOther.getAvailableamount())))
				&& ((this.getRentaldate() == castOther.getRentaldate())
						|| (this.getRentaldate() != null && castOther.getRentaldate() != null
								&& this.getRentaldate().equals(castOther.getRentaldate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMovieid() == null ? 0 : this.getMovieid().hashCode());
		result = 37 * result + (getSystemuserid() == null ? 0 : this.getSystemuserid().hashCode());
		result = 37 * result + (getMoviecode() == null ? 0 : this.getMoviecode().hashCode());
		result = 37 * result + (getAvailableamount() == null ? 0 : this.getAvailableamount().hashCode());
		result = 37 * result + (getRentaldate() == null ? 0 : this.getRentaldate().hashCode());
		return result;
	}

}
