// default package
// Generated Mar 1, 2017 4:12:55 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Moviecopy generated by hbm2java
 */
public class Moviecopy implements java.io.Serializable {

	private BigDecimal moviecopyid;
	private Movie movie;
	private Client client;
	private String moviecode;
	private BigDecimal availableamount;
	private Date rentaldate;

	public Moviecopy() {
	}

	public Moviecopy(BigDecimal moviecopyid, Movie movie, BigDecimal availableamount) {
		this.moviecopyid = moviecopyid;
		this.movie = movie;
		this.availableamount = availableamount;
	}

	public Moviecopy(BigDecimal moviecopyid, Movie movie, Client client, String moviecode, BigDecimal availableamount,
			Date rentaldate) {
		this.moviecopyid = moviecopyid;
		this.movie = movie;
		this.client = client;
		this.moviecode = moviecode;
		this.availableamount = availableamount;
		this.rentaldate = rentaldate;
	}

	public BigDecimal getMoviecopyid() {
		return this.moviecopyid;
	}

	public void setMoviecopyid(BigDecimal moviecopyid) {
		this.moviecopyid = moviecopyid;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public String getMoviecode() {
		return this.moviecode;
	}

	public void setMoviecode(String moviecode) {
		this.moviecode = moviecode;
	}

	public BigDecimal getAvailableamount() {
		return this.availableamount;
	}

	public void setAvailableamount(BigDecimal availableamount) {
		this.availableamount = availableamount;
	}

	public Date getRentaldate() {
		return this.rentaldate;
	}

	public void setRentaldate(Date rentaldate) {
		this.rentaldate = rentaldate;
	}

}
