// default package
// Generated 2017-02-28 18:17:33 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Subscriptiontype generated by hbm2java
 */
public class Subscriptiontype implements java.io.Serializable {

	private String subscriptiontypeid;
	private String name;
	private BigDecimal cost;
	private BigDecimal maxrentals;
	private BigDecimal maxlength;
	private Set subscriptions = new HashSet(0);

	public Subscriptiontype() {
	}

	public Subscriptiontype(String subscriptiontypeid, String name, BigDecimal cost, BigDecimal maxrentals) {
		this.subscriptiontypeid = subscriptiontypeid;
		this.name = name;
		this.cost = cost;
		this.maxrentals = maxrentals;
	}

	public Subscriptiontype(String subscriptiontypeid, String name, BigDecimal cost, BigDecimal maxrentals,
			BigDecimal maxlength, Set subscriptions) {
		this.subscriptiontypeid = subscriptiontypeid;
		this.name = name;
		this.cost = cost;
		this.maxrentals = maxrentals;
		this.maxlength = maxlength;
		this.subscriptions = subscriptions;
	}

	public String getSubscriptiontypeid() {
		return this.subscriptiontypeid;
	}

	public void setSubscriptiontypeid(String subscriptiontypeid) {
		this.subscriptiontypeid = subscriptiontypeid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	public BigDecimal getMaxrentals() {
		return this.maxrentals;
	}

	public void setMaxrentals(BigDecimal maxrentals) {
		this.maxrentals = maxrentals;
	}

	public BigDecimal getMaxlength() {
		return this.maxlength;
	}

	public void setMaxlength(BigDecimal maxlength) {
		this.maxlength = maxlength;
	}

	public Set getSubscriptions() {
		return this.subscriptions;
	}

	public void setSubscriptions(Set subscriptions) {
		this.subscriptions = subscriptions;
	}

}
